### ISSUE TITLE
number seems off

### ISSUE THREAD

**Issue by xstp** [DIVD-NL/observer#1]
https://www.businesswire.com/news/home/20220920006035/en/Verisign-Reports-Internet-Has-351.5-Million-Domain-Name-Registrations-at-the-End-of-the-Second-Quarter-of-2022

**Comment by mrngm** [comment]
What number(s) exactly? The figures from Verisign only include data until June 30, 2022. The reported data in this repository inludes data until November 1, 2022.

.com + .net as reported by Verisign: 174 million
.com + .net as reported by Observer: 180 million

+6 million over 4 months might be a bit off, but that's about 3,4% increase.

The specific figures are also quite close to each other:
.com (Verisign): 161 million (Q2)
.com (Observer): 166 million (Q3.33)
.net (Verisign): 13.2 million (Q2)
.net (Observer): 13.8 million (Q3.33)

**Comment by xstp** [comment]
> What number(s) exactly? The figures from Verisign only include data until June 30, 2022. The reported data in this repository inludes data until November 1, 2022.
> 
> .com + .net as reported by Verisign: 174 million .com + .net as reported by Observer: 180 million
> 
> +6 million over 4 months might be a bit off, but that's about 3,4% increase.
> 
> The specific figures are also quite close to each other: .com (Verisign): 161 million (Q2) .com (Observer): 166 million (Q3.33) .net (Verisign): 13.2 million (Q2) .net (Observer): 13.8 million (Q3.33)

A subset of 1m domains I mass dnssed a while ago only had 40k root domains (e.g. staging.example.com would be in there). It'd be better if we split up fqdn's and domains.

**Comment by xstp** [comment]
noerrors being checked, will open PRs if necessary
